/**
 * Client-side export of generated demo documents.
 * - DOCX: builds a genuine OOXML .docx (minimal zip, no dependencies) — opens in Word, Pages and LibreOffice.
 * - PDF: opens a print-ready letterhead view and triggers the browser "Save as PDF" dialog.
 */

const esc = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

const safeFile = (name: string) =>
  name.replace(/[\\/:*?"<>|]+/g, ' ').replace(/\s+/g, ' ').trim().slice(0, 80) || 'NCEC-document'

const isArabic = (s: string) => /[\u0600-\u06FF]/.test(s)

function strings(ar: boolean) {
  return ar
    ? {
        kingdom: 'المملكة العربية السعودية',
        org: 'المركز الوطني للرقابة على الالتزام البيئي',
        orgSub: 'National Center for Environmental Compliance',
        refNo: 'الرقم المرجعي', dateL: 'التاريخ', templateL: 'القالب', classification: 'التصنيف',
        internal: 'داخلي — مقيد التداول', status: 'الحالة', draft: 'مسودة للمراجعة والاعتماد',
        s1: 'أولاً: التمهيد',
        p1: 'استناداً إلى نظام البيئة الصادر بالمرسوم الملكي رقم (م/165) ولوائحه التنفيذية، وبناءً على الصلاحيات الممنوحة للمركز الوطني للرقابة على الالتزام البيئي، تم إعداد هذه الوثيقة بواسطة منصة الذكاء الاصطناعي للمركز اعتماداً على قاعدة المعرفة الداخلية والوثائق المرجعية المعتمدة.',
        s2: 'ثانياً: المعطيات',
        b1: 'جرت مراجعة الوثائق المرجعية ذات الصلة والتحقق من توافق المحتوى مع اللائحة التنفيذية والمعايير المعتمدة.',
        b2: 'استُخرجت البنود والمتطلبات الجوهرية عبر البحث الدلالي مع إسناد كل فقرة إلى مصدرها ورقم صفحتها.',
        b3: 'روعي في الصياغة القالب المعتمد وضوابط التحرير الرسمية للمركز.',
        s3: 'ثالثاً: التوصية',
        p3: 'يوصى باعتماد ما ورد في هذه الوثيقة بعد استكمال المراجعة النظامية من الإدارة المختصة، مع الأخذ في الاعتبار أن القرار النهائي يظل بيد المسؤول المفوض.',
        disclaimer: 'أُنشئت هذه الوثيقة بواسطة منصة NCEC للذكاء الاصطناعي — المحتوى مستند إلى قاعدة المعرفة الداخلية، والاعتماد النهائي من صلاحية الموظف المفوض.',
        sig1: 'الإدارة المختصة', sig2: 'صاحب الصلاحية', sigName: 'الاسم والتوقيع',
        printHint: 'اختر «حفظ كـ PDF» من نافذة الطباعة', printBtn: 'طباعة / حفظ PDF',
      }
    : {
        kingdom: 'Kingdom of Saudi Arabia',
        org: 'National Center for Environmental Compliance',
        orgSub: 'المركز الوطني للرقابة على الالتزام البيئي',
        refNo: 'Reference No.', dateL: 'Date', templateL: 'Template', classification: 'Classification',
        internal: 'Internal — Restricted', status: 'Status', draft: 'Draft for review & approval',
        s1: '1. Background',
        p1: 'Pursuant to the Environmental Law issued by Royal Decree No. (M/165) and its executive regulations, and under the mandate granted to the National Center for Environmental Compliance, this document was prepared by the Center’s AI Platform based on the internal knowledge base and approved reference documents.',
        s2: '2. Findings',
        b1: 'Relevant reference documents were reviewed and the content was verified against the Executive Regulation and approved standards.',
        b2: 'Key clauses and requirements were retrieved via semantic search, with every passage attributed to its source document and page number.',
        b3: 'The approved template and NCEC official editorial conventions were preserved throughout.',
        s3: '3. Recommendation',
        p3: 'It is recommended to adopt the contents of this document upon completion of the statutory review by the competent department, noting that the final decision remains with the authorized officer.',
        disclaimer: 'Generated by the NCEC AI Platform — content grounded in the internal knowledge base; final approval rests with the authorized officer.',
        sig1: 'Competent Department', sig2: 'Authorized Officer', sigName: 'Name & Signature',
        printHint: 'Choose “Save as PDF” in the print dialog', printBtn: 'Print / Save PDF',
      }
}

const docDate = (ar: boolean) =>
  new Date().toLocaleDateString(ar ? 'ar-SA' : 'en-GB', { year: 'numeric', month: 'long', day: 'numeric' })

const refNumber = (template: string) => `${template}-2026-${String(Math.floor(1000 + Math.random() * 9000))}`

/* ------------------------------------------------------------------ */
/* PDF (print view)                                                    */
/* ------------------------------------------------------------------ */

function buildHtml(title: string, template: string, type: string, forPrint: boolean): string {
  // The document body language follows the document title language, not the UI language.
  const ar = isArabic(title)
  const dir = ar ? 'rtl' : 'ltr'
  const date = docDate(ar)
  const ref = refNumber(template)
  const L = strings(ar)

  const printExtras = forPrint
    ? `<div class="toolbar"><span>${L.printHint}</span><button onclick="window.print()">${L.printBtn}</button></div>
       <script>window.addEventListener('load',function(){setTimeout(function(){window.print()},450)})</script>`
    : ''

  return `<!DOCTYPE html>
<html dir="${dir}" lang="${ar ? 'ar' : 'en'}">
<head>
<meta charset="utf-8">
<title>${esc(safeFile(title))}</title>
<style>
  body { font-family: 'IBM Plex Sans Arabic', 'Segoe UI', Arial, sans-serif; color: #1e293b; margin: 0; background: #fff; }
  .page { max-width: 780px; margin: 0 auto; padding: 36px 44px 48px; }
  .bar { height: 7px; background: #047857; }
  .head { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #047857; padding: 18px 0 14px; }
  .org { font-size: 15px; font-weight: 700; color: #065f46; margin: 0; }
  .org-sub { font-size: 10px; color: #64748b; margin: 3px 0 0; }
  .meta { text-align: ${ar ? 'left' : 'right'}; font-size: 11px; color: #475569; line-height: 1.7; }
  h1 { font-size: 17px; color: #0f172a; margin: 26px 0 4px; }
  .type { font-size: 11px; color: #047857; font-weight: 600; letter-spacing: .4px; margin: 0 0 18px; }
  table.info { width: 100%; border-collapse: collapse; font-size: 11.5px; margin-bottom: 22px; }
  table.info td { border: 1px solid #e2e8f0; padding: 7px 10px; }
  table.info td.k { background: #f8fafc; font-weight: 600; color: #334155; width: 22%; white-space: nowrap; }
  h2 { font-size: 13px; color: #065f46; margin: 22px 0 8px; }
  p, li { font-size: 12.5px; line-height: 1.9; color: #334155; margin: 0 0 10px; }
  ul { padding-${ar ? 'right' : 'left'}: 20px; margin: 0 0 10px; }
  .disclaimer { margin-top: 26px; padding: 10px 14px; background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; font-size: 10.5px; color: #166534; }
  table.sig { width: 100%; margin-top: 40px; font-size: 11.5px; color: #334155; }
  table.sig td { width: 50%; padding-top: 34px; text-align: center; }
  .sig-line { border-top: 1px solid #94a3b8; width: 70%; margin: 0 auto; padding-top: 6px; }
  .toolbar { position: sticky; top: 0; display: flex; justify-content: space-between; align-items: center; gap: 12px; background: #0f172a; color: #e2e8f0; font-size: 12px; padding: 10px 18px; }
  .toolbar button { background: #059669; color: #fff; border: 0; border-radius: 6px; padding: 7px 16px; font-size: 12px; font-weight: 600; cursor: pointer; }
  @media print { .toolbar { display: none; } .page { padding: 0 10px; } }
</style>
</head>
<body>
${printExtras}
<div class="bar"></div>
<div class="page">
  <div class="head">
    <div>
      <p class="org">${L.org}</p>
      <p class="org-sub">${L.orgSub}</p>
    </div>
    <div class="meta">
      ${L.kingdom}<br>
      ${L.refNo}: ${ref}<br>
      ${L.dateL}: ${date}
    </div>
  </div>

  <h1 dir="auto">${esc(title)}</h1>
  <p class="type">${esc(type)} · ${esc(template)}</p>

  <table class="info">
    <tr><td class="k">${L.templateL}</td><td>${esc(template)}</td><td class="k">${L.classification}</td><td>${L.internal}</td></tr>
    <tr><td class="k">${L.status}</td><td>${L.draft}</td><td class="k">${L.dateL}</td><td>${date}</td></tr>
  </table>

  <h2>${L.s1}</h2>
  <p>${L.p1}</p>

  <h2>${L.s2}</h2>
  <ul>
    <li>${L.b1}</li>
    <li>${L.b2}</li>
    <li>${L.b3}</li>
  </ul>

  <h2>${L.s3}</h2>
  <p>${L.p3}</p>

  <div class="disclaimer">${L.disclaimer}</div>

  <table class="sig">
    <tr>
      <td><div class="sig-line">${L.sig1}<br>${L.sigName}</div></td>
      <td><div class="sig-line">${L.sig2}<br>${L.sigName}</div></td>
    </tr>
  </table>
</div>
</body>
</html>`
}

/* ------------------------------------------------------------------ */
/* Real .docx (OOXML) generation — minimal stored ZIP, no dependencies */
/* ------------------------------------------------------------------ */

const CRC_TABLE = (() => {
  const t = new Uint32Array(256)
  for (let n = 0; n < 256; n++) {
    let c = n
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
    t[n] = c >>> 0
  }
  return t
})()

function crc32(data: Uint8Array): number {
  let c = 0xffffffff
  for (let i = 0; i < data.length; i++) c = CRC_TABLE[(c ^ data[i]) & 0xff] ^ (c >>> 8)
  return (c ^ 0xffffffff) >>> 0
}

/** Builds an uncompressed ("stored") ZIP — valid for OOXML packages. */
function zipStore(files: { name: string; data: Uint8Array }[]): Blob {
  const enc = new TextEncoder()
  const parts: Uint8Array[] = []
  const central: Uint8Array[] = []
  let offset = 0

  for (const f of files) {
    const name = enc.encode(f.name)
    const crc = crc32(f.data)

    const local = new Uint8Array(30 + name.length)
    const lv = new DataView(local.buffer)
    lv.setUint32(0, 0x04034b50, true)
    lv.setUint16(4, 20, true)
    lv.setUint16(6, 0x0800, true) // UTF-8 names
    lv.setUint16(8, 0, true) // stored (no compression)
    lv.setUint32(14, crc, true)
    lv.setUint32(18, f.data.length, true)
    lv.setUint32(22, f.data.length, true)
    lv.setUint16(26, name.length, true)
    local.set(name, 30)
    parts.push(local, f.data)

    const cen = new Uint8Array(46 + name.length)
    const cv = new DataView(cen.buffer)
    cv.setUint32(0, 0x02014b50, true)
    cv.setUint16(4, 20, true)
    cv.setUint16(6, 20, true)
    cv.setUint16(8, 0x0800, true)
    cv.setUint16(10, 0, true)
    cv.setUint32(16, crc, true)
    cv.setUint32(20, f.data.length, true)
    cv.setUint32(24, f.data.length, true)
    cv.setUint16(28, name.length, true)
    cv.setUint32(42, offset, true)
    cen.set(name, 46)
    central.push(cen)

    offset += local.length + f.data.length
  }

  const cdSize = central.reduce((s, c) => s + c.length, 0)
  const eocd = new Uint8Array(22)
  const ev = new DataView(eocd.buffer)
  ev.setUint32(0, 0x06054b50, true)
  ev.setUint16(8, files.length, true)
  ev.setUint16(10, files.length, true)
  ev.setUint32(12, cdSize, true)
  ev.setUint32(16, offset, true)

  const all = [...parts, ...central, eocd]
  const total = all.reduce((s, a) => s + a.length, 0)
  const merged = new Uint8Array(total)
  let pos = 0
  for (const chunk of all) {
    merged.set(chunk, pos)
    pos += chunk.length
  }
  return new Blob([merged], {
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  })
}

type ParOpts = {
  bold?: boolean
  size?: number // half-points
  color?: string
  align?: 'center' | 'both'
  after?: number // twips
  borderBottom?: boolean
  rtl?: boolean
}

function par(text: string, o: ParOpts = {}): string {
  const pPr =
    '<w:pPr>' +
    (o.borderBottom ? '<w:pBdr><w:bottom w:val="single" w:sz="18" w:space="6" w:color="047857"/></w:pBdr>' : '') +
    (o.rtl ? '<w:bidi/>' : '') +
    `<w:spacing w:after="${o.after ?? 120}" w:line="300" w:lineRule="auto"/>` +
    (o.align ? `<w:jc w:val="${o.align}"/>` : '') +
    '</w:pPr>'
  const sz = o.size ?? 22
  const rPr =
    '<w:rPr>' +
    '<w:rFonts w:ascii="Calibri" w:hAnsi="Calibri" w:cs="Arial"/>' +
    (o.bold ? '<w:b/><w:bCs/>' : '') +
    (o.color ? `<w:color w:val="${o.color}"/>` : '') +
    `<w:sz w:val="${sz}"/><w:szCs w:val="${sz}"/>` +
    (o.rtl ? '<w:rtl/>' : '') +
    '</w:rPr>'
  return `<w:p>${pPr}<w:r>${rPr}<w:t xml:space="preserve">${esc(text)}</w:t></w:r></w:p>`
}

/** Exported for validation tests as well as the download handler. */
export function buildDocxBlob(title: string, template: string, type: string): Blob {
  const ar = isArabic(title)
  const L = strings(ar)
  const date = docDate(ar)
  const ref = refNumber(template)

  const body: string[] = [
    par(L.org, { bold: true, size: 28, color: '065F46', rtl: ar, after: 40 }),
    par(L.orgSub, { size: 18, color: '64748B', rtl: ar, after: 80 }),
    par(`${L.kingdom} · ${L.refNo}: ${ref} · ${L.dateL}: ${date}`, { size: 18, color: '475569', rtl: ar, after: 240, borderBottom: true }),
    par(title, { bold: true, size: 32, color: '0F172A', rtl: ar, after: 60 }),
    par(`${type} · ${template}`, { bold: true, size: 18, color: '047857', rtl: ar, after: 80 }),
    par(`${L.classification}: ${L.internal} · ${L.status}: ${L.draft}`, { size: 18, color: '64748B', rtl: ar, after: 280 }),
    par(L.s1, { bold: true, size: 24, color: '065F46', rtl: ar, after: 80 }),
    par(L.p1, { size: 22, color: '334155', align: 'both', rtl: ar, after: 200 }),
    par(L.s2, { bold: true, size: 24, color: '065F46', rtl: ar, after: 80 }),
    par(`•  ${L.b1}`, { size: 22, color: '334155', rtl: ar, after: 80 }),
    par(`•  ${L.b2}`, { size: 22, color: '334155', rtl: ar, after: 80 }),
    par(`•  ${L.b3}`, { size: 22, color: '334155', rtl: ar, after: 200 }),
    par(L.s3, { bold: true, size: 24, color: '065F46', rtl: ar, after: 80 }),
    par(L.p3, { size: 22, color: '334155', align: 'both', rtl: ar, after: 280 }),
    par(L.disclaimer, { size: 18, color: '166534', rtl: ar, after: 600 }),
    par('________________________', { size: 22, color: '334155', align: 'center', after: 40 }),
    par(`${L.sig1} — ${L.sigName}`, { size: 18, color: '475569', align: 'center', rtl: ar, after: 400 }),
    par('________________________', { size: 22, color: '334155', align: 'center', after: 40 }),
    par(`${L.sig2} — ${L.sigName}`, { size: 18, color: '475569', align: 'center', rtl: ar, after: 40 }),
  ]

  const documentXml =
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
    '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">' +
    `<w:body>${body.join('')}` +
    '<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134" w:header="708" w:footer="708" w:gutter="0"/></w:sectPr>' +
    '</w:body></w:document>'

  const contentTypes =
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
    '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">' +
    '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>' +
    '<Default Extension="xml" ContentType="application/xml"/>' +
    '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>' +
    '<Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>' +
    '</Types>'

  const rels =
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' +
    '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>' +
    '</Relationships>'

  const wordRels =
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' +
    '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>' +
    '</Relationships>'

  const stylesXml =
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
    '<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">' +
    '<w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri" w:cs="Arial"/></w:rPr></w:rPrDefault></w:docDefaults>' +
    '</w:styles>'

  const enc = new TextEncoder()
  return zipStore([
    { name: '[Content_Types].xml', data: enc.encode(contentTypes) },
    { name: '_rels/.rels', data: enc.encode(rels) },
    { name: 'word/document.xml', data: enc.encode(documentXml) },
    { name: 'word/_rels/document.xml.rels', data: enc.encode(wordRels) },
    { name: 'word/styles.xml', data: enc.encode(stylesXml) },
  ])
}

/* ------------------------------------------------------------------ */
/* Public API                                                          */
/* ------------------------------------------------------------------ */

export function downloadWord(title: string, template: string, type: string) {
  const blob = buildDocxBlob(title, template, type)
  const filename = `${safeFile(title)}.docx`

  // Legacy Edge / IE
  const nav = navigator as Navigator & { msSaveOrOpenBlob?: (b: Blob, n: string) => void }
  if (nav.msSaveOrOpenBlob) {
    nav.msSaveOrOpenBlob(blob, filename)
    return
  }

  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.style.display = 'none'
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 10000)
}

export function downloadPdf(title: string, template: string, type: string) {
  const html = buildHtml(title, template, type, true)
  const win = window.open('', '_blank')
  if (!win) return
  win.document.open()
  win.document.write(html)
  win.document.close()
}
